/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package d_riqqi;

import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Riqqi
 */
public class Pert2TugasLab2Riqqi extends javax.swing.JFrame {

    /**
     * Creates new form Pert2TugasLab2Riqqi
     */
    public Pert2TugasLab2Riqqi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupLokasi = new javax.swing.ButtonGroup();
        groupUsia = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        radioPkl = new javax.swing.JRadioButton();
        radioJateng = new javax.swing.JRadioButton();
        radioLuarJawa = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        radioUsia1 = new javax.swing.JRadioButton();
        radioUsia2 = new javax.swing.JRadioButton();
        radioUsia3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        checkInformasi = new javax.swing.JCheckBox();
        checkDanaSegar = new javax.swing.JCheckBox();
        checkCariJodoh = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SEMINAR MENGUBAH SISWA MENJADI PINTAR DAN MANDIRI");

        jLabel2.setText("NAMA PESERTA SEMINAR ");

        jLabel3.setText("EMAIL PESERTA");

        jLabel4.setText("STMIK WIDYA PRATAMA PEKALONGAN");

        jLabel5.setText("LOKASI TINGGAL");

        groupLokasi.add(radioPkl);
        radioPkl.setText("PEKALONGAN");

        groupLokasi.add(radioJateng);
        radioJateng.setText("JAWA TENGAH");

        groupLokasi.add(radioLuarJawa);
        radioLuarJawa.setText("LUAR JAWA");

        jLabel6.setText("USIA PESERTA");

        groupUsia.add(radioUsia1);
        radioUsia1.setText("17 - 25 TAHUN");

        groupUsia.add(radioUsia2);
        radioUsia2.setText("26 - 45 TAHUN");

        groupUsia.add(radioUsia3);
        radioUsia3.setText("46 - 70 TAHUN");

        jLabel7.setText("KEPERLUAN SEMINAR");

        checkInformasi.setText("INFORMASI");

        checkDanaSegar.setText("DAPAT DANA SEGAR");

        checkCariJodoh.setText("CARI JODOH");

        jButton1.setText("PROSES PESERTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioPkl)
                                        .addGap(70, 70, 70)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioJateng)
                                            .addComponent(radioUsia2)
                                            .addComponent(checkDanaSegar))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(textNama)
                                    .addComponent(textEmail)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(137, 137, 137)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkInformasi)
                                            .addComponent(radioUsia1)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(14, 14, 14)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioLuarJawa)
                                    .addComponent(radioUsia3)
                                    .addComponent(checkCariJodoh))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 122, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(150, 150, 150))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(178, 178, 178))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(radioPkl)
                    .addComponent(radioJateng)
                    .addComponent(radioLuarJawa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(radioUsia1)
                    .addComponent(radioUsia2)
                    .addComponent(radioUsia3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(checkInformasi)
                    .addComponent(checkDanaSegar)
                    .addComponent(checkCariJodoh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nama = textNama.getText();
        String email = textEmail.getText();
        String lokasi = "";
        String usia = "";
        String informasi = "";

        String hasil = "";
        if (radioJateng.isSelected()) {
            lokasi = "Jawa Tengah  (dekat)";
        } else if (radioLuarJawa.isSelected()) {
            lokasi = "Luar Jawa   (jauh ini)";
        } else if (radioPkl.isSelected()) {
            lokasi = "pekalongan (dekat sekali)";
        }

        if (radioUsia1.isSelected()) {
            usia = "17 - 25 tahun";
        } else if (radioUsia2.isSelected()) {
            usia = "26 - 45 tahun ";
        } else if (radioUsia3.isSelected()) {
            usia = "46 - 70 tahun (udah tua)";
        }

        if (checkInformasi.isSelected()) {
            informasi += "\n      - INFORMASI (sipaling niat)";
        }
        if (checkDanaSegar.isSelected()) {
            informasi += "\n      - DANA SEGAR (sipaling cari uang)";
        }
        if (checkCariJodoh.isSelected()) {
            informasi += "\n      - CARI JODOH (ga niat seminar)";
        }

        hasil += "\n      FORM SEMINAR";
        hasil += "\n NAMA      : " + nama;
        hasil += "\n EMAIL     : " + email;
        hasil += "\n LOKASI    : " + lokasi;
        hasil += "\n USIA      : " + usia;
        hasil += "\n KEPERLUAN : " + informasi;
        JOptionPane.showMessageDialog(this, hasil);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pert2TugasLab2Riqqi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pert2TugasLab2Riqqi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pert2TugasLab2Riqqi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pert2TugasLab2Riqqi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Font font = new Font("Monospaced", Font.PLAIN, 15);
        //For MessageArea and TextField font.
        UIManager.put("OptionPane.messageFont", font);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pert2TugasLab2Riqqi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkCariJodoh;
    private javax.swing.JCheckBox checkDanaSegar;
    private javax.swing.JCheckBox checkInformasi;
    private javax.swing.ButtonGroup groupLokasi;
    private javax.swing.ButtonGroup groupUsia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton radioJateng;
    private javax.swing.JRadioButton radioLuarJawa;
    private javax.swing.JRadioButton radioPkl;
    private javax.swing.JRadioButton radioUsia1;
    private javax.swing.JRadioButton radioUsia2;
    private javax.swing.JRadioButton radioUsia3;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textNama;
    // End of variables declaration//GEN-END:variables
}
