/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package d_riqqi;

import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Riqqi
 */
public class TugasMandiri2Riqqi extends javax.swing.JFrame {

    /**
     * Creates new form TugasMandiri2Riqqi
     */
    public TugasMandiri2Riqqi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tInput = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tugas Mandiri 2 Riqqi");

        jLabel2.setText("Masukkan angka [1-7]");

        jButton1.setText("AYOO!!");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tInput, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int inputan = Integer.parseInt(tInput.getText());

            if (inputan >= 1 && inputan <= 7) {

                int awal = 1, angkaMendatar = 12, angkaSamping = 0;
                int angkaTengah = 0, spasi = 7, printSpasi = 0, angkaTampilTengah = 0;
                String tampil = "";

                do {
                    angkaSamping = awal;
                    angkaMendatar = angkaSamping + 11;
                    angkaTengah = angkaSamping + 2;
                    angkaTampilTengah = angkaTengah;
                    printSpasi = spasi;
                    int angkaAkhir = 0;
                    for (; angkaSamping >= 1; angkaSamping--) {
                        tampil += angkaMendatar + " ";
                        angkaAkhir += angkaMendatar;
                        angkaMendatar++;
                    }
                    for (; angkaTampilTengah >= 3; angkaTampilTengah--) {
                        tampil += angkaTampilTengah + " ";
                        angkaAkhir += angkaTampilTengah;
                    }
                    for (; printSpasi >= 1; printSpasi--) {
                        tampil += "     ";
                        System.out.print("     ");
                    }
                    tampil += " = " + angkaAkhir + "\n";
                    awal++;
                    spasi--;

                } while (awal <= inputan);
                JOptionPane.showMessageDialog(null, tampil);

            } else {
                JOptionPane.showMessageDialog(this, "ANGKA YANG DIMASUKKAN TIDAK SESUAI");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "MASUKKAN ANGKA SAJA DONG");
        }
        tInput.requestFocus();
        tInput.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        Font font = new Font("Monospaced", Font.PLAIN, 15);
//For MessageArea and TextField font.
        UIManager.put("OptionPane.messageFont", font);
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TugasMandiri2Riqqi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tInput;
    // End of variables declaration//GEN-END:variables
}
